// ══════════════════════════════════════════════════════
//  aptModel.js — APT 5-factor Ridge Model Client
//
//  Consumes data/backtest/mra_apt_coefficients.json (generated by
//  scripts/mra_apt_extended.py) to provide runtime APT-augmented
//  predicted-return estimates for pattern occurrences.
//
//  Academic basis:
//    - Ross (1976): Arbitrage Pricing Theory (multi-factor)
//    - Sharpe (1964): CAPM beta_60d
//    - Fama & French (1993): HML (value_inv_pbr), SMB (log_size)
//    - Jegadeesh & Titman (1993): momentum_60d
//    - Amihud (2002): liquidity_20d
//
//  Feature vector (17-col + 1 intercept):
//    [intercept, hw, vw, mw, rw,
//     confidence_norm, signal_dir, market_type, log_confidence, pattern_tier,
//     hw_x_signal, vw_x_signal, conf_x_signal,
//     momentum_60d, beta_60d, value_inv_pbr, log_size, liquidity_20d]
//
//  APT factors are z-scored in the offline pipeline. Client callers must
//  supply already-standardized values (z-score vs the training cohort) or
//  pass null to set factor contribution to zero.
// ══════════════════════════════════════════════════════

var aptModel = (function() {
  var _coefficients = null;
  var _featureNames = null;
  var _aptFactorsMeta = null;
  var _nSamples = 0;
  var _horizon = 5;
  var _lambda = 2.0;
  var _loaded = false;
  var _loading = null;
  var _loadFailed = false;

  function _loadCoefficients() {
    if (_loading) return _loading;
    if (_loaded) return Promise.resolve();
    // [V48-SEC Phase 7 P7-001] Coefficients moved behind /api/apt (HMAC+Origin).
    // Prefer _signGet when sign.js is loaded; fall back to plain fetch only if
    // running in a context without session wiring (e.g. standalone tests).
    var _fetch = (typeof self !== 'undefined' && typeof self._signGet === 'function')
      ? self._signGet('/api/apt')
      : fetch('/api/apt', { cache: 'no-store', credentials: 'same-origin' });
    _loading = _fetch
      .then(function(r) {
        if (!r.ok) throw new Error('HTTP ' + r.status);
        return r.json();
      })
      .then(function(data) {
        if (!data || !Array.isArray(data.coefficients) || data.coefficients.length !== 18) {
          throw new Error('APT schema invalid: expected 18 coefficients, got ' +
                          (data && data.coefficients ? data.coefficients.length : 'null'));
        }
        _coefficients = data.coefficients;
        _featureNames = data.feature_names;
        _aptFactorsMeta = data.apt_factors || {};
        _nSamples = data.n_samples || 0;
        _horizon = data.horizon || 5;
        _lambda = data.lambda || 2.0;
        _loaded = true;
        _loadFailed = false;
        console.log('[APT] Model loaded: 17-col Ridge (λ=' + _lambda +
                    ', horizon=' + _horizon + 'd, n=' + _nSamples + ')');
        return data;
      })
      .catch(function(err) {
        _loadFailed = true;
        _loading = null;
        console.warn('[APT] Load failed:', err && err.message ? err.message : err);
        throw err;
      });
    return _loading;
  }

  /**
   * Compute APT-augmented prediction (% return at horizon=5d) for a pattern occurrence.
   * Returns null if model not loaded or inputs incomplete.
   *
   * @param {Object} features
   *   .confidence  - base confidence 0-100
   *   .signal      - 'buy' | 'sell' | 'neutral'
   *   .marketType  - 'kospi' | 'kosdaq'
   *   .hw, .vw, .mw, .rw - Wc weights (default 1.0)
   *   .patternTier - tier code (default 0)
   *   .momentum60d, .beta60d, .valueInvPbr, .logSize, .liquidity20d
   *      - z-scored APT factors (null → zero contribution)
   */
  function predict(features) {
    if (!_loaded || !_coefficients) return null;

    var f = features || {};
    var conf = Math.max(1, Math.min(100, f.confidence != null ? f.confidence : 50));
    var confNorm = conf / 100;
    var signalDir = f.signal === 'buy' ? 1 : f.signal === 'sell' ? -1 : 0;
    var marketType = f.marketType === 'kospi' ? 1 : 0;
    var logConf = Math.log(Math.max(1e-6, conf));
    var tier = f.patternTier != null ? f.patternTier : 0;
    var hw = f.hw != null ? f.hw : 1;
    var vw = f.vw != null ? f.vw : 1;
    var mw = f.mw != null ? f.mw : 1;
    var rw = f.rw != null ? f.rw : 1;

    var vec = [
      1,                                                    // 0 intercept
      hw, vw, mw, rw,                                        // 1-4 Wc
      confNorm, signalDir, marketType, logConf, tier,        // 5-9 confidence/signal
      hw * signalDir, vw * signalDir, confNorm * signalDir,  // 10-12 interactions
      f.momentum60d != null ? f.momentum60d : 0,             // 13 APT: momentum
      f.beta60d != null ? f.beta60d : 0,                     // 14 APT: beta
      f.valueInvPbr != null ? f.valueInvPbr : 0,             // 15 APT: value (1/PBR)
      f.logSize != null ? f.logSize : 0,                     // 16 APT: size (log mcap)
      f.liquidity20d != null ? f.liquidity20d : 0            // 17 APT: liquidity
    ];

    var pred = 0;
    for (var i = 0; i < vec.length; i++) {
      pred += _coefficients[i] * vec[i];
    }
    return pred;
  }

  /**
   * Compute per-stock APT factor vector from raw market data.
   * [V48-SEC Phase 7 P7-001] Per-factor gates replace global idx<60 gate so
   * short-history stocks still contribute value_inv_pbr / log_size.
   *
   * @param {Array} candles - OHLCV array (daily)
   * @param {number} idx    - occurrence index in candles
   * @param {Object} meta   - { marketCap, pbr, marketReturns60d? }
   * @returns {Object|null} - { momentum60d, beta60d, valueInvPbr, logSize, liquidity20d }
   *                          Fields may be null individually; object itself null only if idx invalid.
   */
  function computeFactors(candles, idx, meta) {
    if (!candles || idx == null || idx < 0 || idx >= candles.length) return null;
    meta = meta || {};

    var out = {
      momentum60d: null,
      beta60d: null,
      valueInvPbr: null,
      logSize: null,
      liquidity20d: null
    };

    // momentum_60d: 60-day return (requires idx >= 60)
    if (idx >= 60) {
      var p0 = candles[idx - 60] && candles[idx - 60].close;
      var pT = candles[idx] && candles[idx].close;
      if (p0 > 0 && pT > 0) {
        out.momentum60d = (pT / p0 - 1) * 100;
      }
    }

    // beta_60d: requires market returns co-series (caller must supply)
    if (idx >= 60
        && Array.isArray(meta.marketReturns60d)
        && meta.marketReturns60d.length === 60
        && meta.marketReturns60d.every(function(r) { return typeof r === 'number' && isFinite(r); })) {
      var stockRets = [];
      for (var i = idx - 59; i <= idx; i++) {
        var pPrev = candles[i - 1] && candles[i - 1].close;
        var pCur = candles[i] && candles[i].close;
        if (pPrev > 0 && pCur > 0) stockRets.push(Math.log(pCur / pPrev));
        else stockRets.push(0);
      }
      var mktRets = meta.marketReturns60d;
      var mS = 0, mM = 0;
      for (var j = 0; j < 60; j++) { mS += stockRets[j]; mM += mktRets[j]; }
      mS /= 60; mM /= 60;
      var cov = 0, varM = 0;
      for (var k = 0; k < 60; k++) {
        cov += (stockRets[k] - mS) * (mktRets[k] - mM);
        varM += (mktRets[k] - mM) * (mktRets[k] - mM);
      }
      if (varM > 1e-10) out.beta60d = cov / varM;
    }

    // value_inv_pbr: 1/PBR, gate pbr > 0.01 (matches training L.331 -- prevents
    // 1/pbr explosion for near-zero/negative book value)
    if (typeof meta.pbr === 'number' && isFinite(meta.pbr) && meta.pbr > 0.01) {
      out.valueInvPbr = 1 / meta.pbr;
    }

    // log_size: log(marketCap in 억원)
    if (typeof meta.marketCap === 'number' && isFinite(meta.marketCap) && meta.marketCap > 0) {
      out.logSize = Math.log(meta.marketCap);
    }

    // liquidity_20d: 20-day avg turnover × 100 (training L.350 unit parity).
    // Require count >= 10 trading days (tolerate up to 11 suspension days).
    if (typeof meta.marketCap === 'number' && meta.marketCap > 0 && idx >= 19) {
      var sumTurnover = 0;
      var count = 0;
      for (var w = idx - 19; w <= idx; w++) {
        var c = candles[w];
        if (c && c.close > 0 && c.volume > 0) {
          sumTurnover += (c.close * c.volume) / (meta.marketCap * 1e8); // 억원 → 원
          count++;
        }
      }
      if (count >= 10) out.liquidity20d = (sumTurnover / count) * 100;
    }

    return out;
  }

  /**
   * Cohort robust z-score: match training pipeline's per-date normalization
   * (scripts/mra_apt_extended.py L.382-393) using median + MAD*1.4826.
   * Winsorize to [-3, 3]. Null raws and null factor values → 0 contribution.
   *
   * Design note: training uses per-date cross-sectional stats. Client replicates
   * the formula (not the exact values) on the runtime cohort — math symmetry
   * preserved, distribution shift acknowledged. μ/σ never persisted.
   *
   * @param {Array<Object|null>} rawList - output of computeFactors per occurrence
   * @returns {Array<Object>} - same length; each entry has 5 finite z-scored factors
   */
  function zscoreCohort(rawList) {
    var zero = function() {
      return { momentum60d: 0, beta60d: 0, valueInvPbr: 0, logSize: 0, liquidity20d: 0 };
    };
    var n = rawList ? rawList.length : 0;
    if (n < 5) return rawList ? rawList.map(zero) : [];

    var factors = ['momentum60d', 'beta60d', 'valueInvPbr', 'logSize', 'liquidity20d'];
    var params = {};

    for (var f = 0; f < factors.length; f++) {
      var fname = factors[f];
      var vals = [];
      for (var i = 0; i < n; i++) {
        var r = rawList[i];
        if (r) {
          var v = r[fname];
          if (typeof v === 'number' && isFinite(v)) vals.push(v);
        }
      }
      if (vals.length < 3) { params[fname] = null; continue; }
      vals.sort(function(a, b) { return a - b; });
      var median = vals[Math.floor(vals.length / 2)];
      var absdev = [];
      for (var j = 0; j < vals.length; j++) absdev.push(Math.abs(vals[j] - median));
      absdev.sort(function(a, b) { return a - b; });
      var mad = absdev[Math.floor(absdev.length / 2)];
      var scale = (mad > 1e-10) ? (mad * 1.4826) : null;
      if (scale == null) {
        // MAD == 0 (>50% values identical): fall back to sample std
        var mean = 0;
        for (var k = 0; k < vals.length; k++) mean += vals[k];
        mean /= vals.length;
        var sumSq = 0;
        for (var l = 0; l < vals.length; l++) sumSq += (vals[l] - mean) * (vals[l] - mean);
        var std = Math.sqrt(sumSq / Math.max(vals.length - 1, 1));
        scale = (std > 1e-10) ? std : null;
      }
      params[fname] = (scale && scale > 1e-10) ? { median: median, scale: scale } : null;
    }

    var out = [];
    for (var m = 0; m < n; m++) {
      var raw = rawList[m];
      var e = zero();
      if (raw) {
        for (var fi = 0; fi < factors.length; fi++) {
          var fn = factors[fi];
          var val = raw[fn];
          var p = params[fn];
          if (p && typeof val === 'number' && isFinite(val)) {
            var z = (val - p.median) / p.scale;
            if (z > 3) z = 3; else if (z < -3) z = -3;
            e[fn] = z;
          }
        }
      }
      out.push(e);
    }
    return out;
  }

  function isLoaded() { return _loaded; }
  function hasFailed() { return _loadFailed; }
  function getMeta() {
    return {
      featureNames: _featureNames,
      aptFactors: _aptFactorsMeta,
      nSamples: _nSamples,
      horizon: _horizon,
      lambda: _lambda,
      coefCount: _coefficients ? _coefficients.length : 0
    };
  }
  function init() { return _loadCoefficients(); }

  return {
    init: init,
    predict: predict,
    computeFactors: computeFactors,
    zscoreCohort: zscoreCohort,
    isLoaded: isLoaded,
    hasFailed: hasFailed,
    getMeta: getMeta
  };
})();

// Auto-init on script load (non-blocking; silent retry-on-demand via init())
if (typeof fetch !== 'undefined') {
  aptModel.init().catch(function() { /* swallow — calls will return null */ });
}
