// ══════════════════════════════════════════════════════
//  aptModel.js — APT 5-factor Ridge Model Client
//
//  Consumes data/backtest/mra_apt_coefficients.json (generated by
//  scripts/mra_apt_extended.py) to provide runtime APT-augmented
//  predicted-return estimates for pattern occurrences.
//
//  Academic basis:
//    - Ross (1976): Arbitrage Pricing Theory (multi-factor)
//    - Sharpe (1964): CAPM beta_60d
//    - Fama & French (1993): HML (value_inv_pbr), SMB (log_size)
//    - Jegadeesh & Titman (1993): momentum_60d
//    - Amihud (2002): liquidity_20d
//
//  Feature vector (17-col + 1 intercept):
//    [intercept, hw, vw, mw, rw,
//     confidence_norm, signal_dir, market_type, log_confidence, pattern_tier,
//     hw_x_signal, vw_x_signal, conf_x_signal,
//     momentum_60d, beta_60d, value_inv_pbr, log_size, liquidity_20d]
//
//  APT factors are z-scored in the offline pipeline. Client callers must
//  supply already-standardized values (z-score vs the training cohort) or
//  pass null to set factor contribution to zero.
// ══════════════════════════════════════════════════════

var aptModel = (function() {
  var _coefficients = null;
  var _featureNames = null;
  var _aptFactorsMeta = null;
  var _nSamples = 0;
  var _horizon = 5;
  var _lambda = 2.0;
  var _loaded = false;
  var _loading = null;
  var _loadFailed = false;

  function _loadCoefficients() {
    if (_loading) return _loading;
    if (_loaded) return Promise.resolve();
    _loading = fetch('/data/backtest/mra_apt_coefficients.json', { cache: 'default' })
      .then(function(r) {
        if (!r.ok) throw new Error('HTTP ' + r.status);
        return r.json();
      })
      .then(function(data) {
        if (!data || !Array.isArray(data.coefficients) || data.coefficients.length !== 18) {
          throw new Error('APT schema invalid: expected 18 coefficients, got ' +
                          (data && data.coefficients ? data.coefficients.length : 'null'));
        }
        _coefficients = data.coefficients;
        _featureNames = data.feature_names;
        _aptFactorsMeta = data.apt_factors || {};
        _nSamples = data.n_samples || 0;
        _horizon = data.horizon || 5;
        _lambda = data.lambda || 2.0;
        _loaded = true;
        _loadFailed = false;
        console.log('[APT] Model loaded: 17-col Ridge (λ=' + _lambda +
                    ', horizon=' + _horizon + 'd, n=' + _nSamples + ')');
        return data;
      })
      .catch(function(err) {
        _loadFailed = true;
        _loading = null;
        console.warn('[APT] Load failed:', err && err.message ? err.message : err);
        throw err;
      });
    return _loading;
  }

  /**
   * Compute APT-augmented prediction (% return at horizon=5d) for a pattern occurrence.
   * Returns null if model not loaded or inputs incomplete.
   *
   * @param {Object} features
   *   .confidence  - base confidence 0-100
   *   .signal      - 'buy' | 'sell' | 'neutral'
   *   .marketType  - 'kospi' | 'kosdaq'
   *   .hw, .vw, .mw, .rw - Wc weights (default 1.0)
   *   .patternTier - tier code (default 0)
   *   .momentum60d, .beta60d, .valueInvPbr, .logSize, .liquidity20d
   *      - z-scored APT factors (null → zero contribution)
   */
  function predict(features) {
    if (!_loaded || !_coefficients) return null;

    var f = features || {};
    var conf = Math.max(1, Math.min(100, f.confidence != null ? f.confidence : 50));
    var confNorm = conf / 100;
    var signalDir = f.signal === 'buy' ? 1 : f.signal === 'sell' ? -1 : 0;
    var marketType = f.marketType === 'kospi' ? 1 : 0;
    var logConf = Math.log(Math.max(1e-6, conf));
    var tier = f.patternTier != null ? f.patternTier : 0;
    var hw = f.hw != null ? f.hw : 1;
    var vw = f.vw != null ? f.vw : 1;
    var mw = f.mw != null ? f.mw : 1;
    var rw = f.rw != null ? f.rw : 1;

    var vec = [
      1,                                                    // 0 intercept
      hw, vw, mw, rw,                                        // 1-4 Wc
      confNorm, signalDir, marketType, logConf, tier,        // 5-9 confidence/signal
      hw * signalDir, vw * signalDir, confNorm * signalDir,  // 10-12 interactions
      f.momentum60d != null ? f.momentum60d : 0,             // 13 APT: momentum
      f.beta60d != null ? f.beta60d : 0,                     // 14 APT: beta
      f.valueInvPbr != null ? f.valueInvPbr : 0,             // 15 APT: value (1/PBR)
      f.logSize != null ? f.logSize : 0,                     // 16 APT: size (log mcap)
      f.liquidity20d != null ? f.liquidity20d : 0            // 17 APT: liquidity
    ];

    var pred = 0;
    for (var i = 0; i < vec.length; i++) {
      pred += _coefficients[i] * vec[i];
    }
    return pred;
  }

  /**
   * Compute per-stock APT factor vector from raw market data.
   * Returns null if data insufficient. Caller should z-score before predict()
   * if consistent with training cohort normalization is required.
   *
   * @param {Array} candles - OHLCV array (daily)
   * @param {number} idx    - occurrence index in candles
   * @param {Object} meta   - { marketCap, pbr, marketReturns60d? }
   * @returns {Object|null} - { momentum60d, beta60d, valueInvPbr, logSize, liquidity20d }
   */
  function computeFactors(candles, idx, meta) {
    if (!candles || idx == null || idx < 60 || idx >= candles.length) return null;
    meta = meta || {};

    var out = {
      momentum60d: null,
      beta60d: null,
      valueInvPbr: null,
      logSize: null,
      liquidity20d: null
    };

    // momentum_60d: 60-day return
    var p0 = candles[idx - 60] && candles[idx - 60].close;
    var pT = candles[idx] && candles[idx].close;
    if (p0 > 0 && pT > 0) {
      out.momentum60d = (pT / p0 - 1) * 100;
    }

    // beta_60d: requires market returns co-series — omit unless supplied
    if (Array.isArray(meta.marketReturns60d) && meta.marketReturns60d.length === 60) {
      var stockRets = [];
      for (var i = idx - 59; i <= idx; i++) {
        var pPrev = candles[i - 1] && candles[i - 1].close;
        var pCur = candles[i] && candles[i].close;
        if (pPrev > 0 && pCur > 0) stockRets.push(Math.log(pCur / pPrev));
        else stockRets.push(0);
      }
      var mktRets = meta.marketReturns60d;
      var mS = 0, mM = 0;
      for (var j = 0; j < 60; j++) { mS += stockRets[j]; mM += mktRets[j]; }
      mS /= 60; mM /= 60;
      var cov = 0, varM = 0;
      for (var k = 0; k < 60; k++) {
        cov += (stockRets[k] - mS) * (mktRets[k] - mM);
        varM += (mktRets[k] - mM) * (mktRets[k] - mM);
      }
      out.beta60d = varM > 0 ? cov / varM : null;
    }

    // value_inv_pbr: 1/PBR (caller supplies pbr from financials)
    if (meta.pbr > 0) out.valueInvPbr = 1 / meta.pbr;

    // log_size: log(marketCap in 억원)
    if (meta.marketCap > 0) out.logSize = Math.log(meta.marketCap);

    // liquidity_20d: 20-day avg turnover (volume × close / marketCap)
    if (meta.marketCap > 0 && idx >= 19) {
      var sumTurnover = 0;
      var count = 0;
      for (var w = idx - 19; w <= idx; w++) {
        var c = candles[w];
        if (c && c.close > 0 && c.volume > 0) {
          sumTurnover += (c.close * c.volume) / (meta.marketCap * 1e8); // 억원 → 원
          count++;
        }
      }
      if (count > 0) out.liquidity20d = sumTurnover / count;
    }

    return out;
  }

  function isLoaded() { return _loaded; }
  function hasFailed() { return _loadFailed; }
  function getMeta() {
    return {
      featureNames: _featureNames,
      aptFactors: _aptFactorsMeta,
      nSamples: _nSamples,
      horizon: _horizon,
      lambda: _lambda,
      coefCount: _coefficients ? _coefficients.length : 0
    };
  }
  function init() { return _loadCoefficients(); }

  return {
    init: init,
    predict: predict,
    computeFactors: computeFactors,
    isLoaded: isLoaded,
    hasFailed: hasFailed,
    getMeta: getMeta
  };
})();

// Auto-init on script load (non-blocking; silent retry-on-demand via init())
if (typeof fetch !== 'undefined') {
  aptModel.init().catch(function() { /* swallow — calls will return null */ });
}
